default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: mimi_server_development

test:
  <<: *default
  database: mimi_server_test

production:
  <<: *default
  database: mimi_server_production
  username: mimi_server
  password: <%= ENV['MIMI_SERVER_DATABASE_PASSWORD'] %>
